apiVersion: apps/v1
kind: Deployment
metadata:
  name: puma
spec:
  replicas: 2
  selector:
    matchLabels:
      app: puma
  template:
    metadata:
      labels:
        app: puma
    spec:
      containers:
      - name: puma
        image: puma-local
        imagePullPolicy: Never
        ports:
          - containerPort: 9292
          - containerPort: 9293

          # - name: http-port
          #   containerPort: 9292
          #   hostPort: 9292
          # - name: control-port
          #   containerPort: 9293
          #   hostPort: 9293
        resources:
          limits:
            memory: "128Mi"
          requests:
            memory: "128Mi"
        env:
          - name: WEB_CONCURRENCY
            value: "0"
          - name: RAILS_MAX_THREADS
            value: "5"
          - name: WAIT_FACTOR
            value: "200"

