apiVersion: apps/v1
kind: Deployment
metadata:
  name: puma
spec:
  replicas: 2
  selector:
    matchLabels:
      app: puma
  template:
    metadata:
      labels:
        app: puma
    spec:
      containers:
      - name: puma
        image: puma-local
        imagePullPolicy: Never
        ports:
        - containerPort: 9292
        resources:
          limits:
            memory: "256Mi"
          requests:
            memory: "128Mi"
        env:
          - name: WEB_CONCURRENCY
            value: "1"
          - name: RAILS_MAX_THREADS
            value: "5"

